spring:
  application:
    name: api-gateway

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: false
#        trace: false

  sql:
    init:
      mode: ${SQL_MODE}
      schema-locations: classpath:schema.sql # runs 1st to create tables
      # data-locations: classpath:data.sql # runs 2nd
      # platform: h2

#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: none
#    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}


server:
  port: ${APP_PORT}

logging:
  level:
    org.springframework.jdbc: ${LOGGING_LEVEL}

mailgun:
  api-key: ${MAILGUN_API_KEY}
  base-url: ${MAILGUN_BASE_URL}
  sandbox: ${MAILGUN_SANDBOX}
  from: ${MAILGUN_FROM}


