spring:
  application:
    name: api-gateway

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    hikari:
      keepalive-time: 30_000
      minimum-idle: 10

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      ssl:
        enabled: ${REDIS_SSL:false}

  sql:
    init:
      mode: ${SQL_MODE}
      schema-locations: classpath:schema.sql

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

server:
  port: ${APP_PORT}

logging:
  config: classpath:api-gateway-logback-spring.xml
  level:
    root: INFO
    com.bicosteve.api_gateway: ${APP_LOGGING}
    org.springframework.jdbc: ${LOGGING_LEVEL}
    org.apache.coyote: ${APP_LOGGING}

mailgun:
  api-key: ${MAILGUN_API_KEY}
  base-url: ${MAILGUN_BASE_URL}
  sandbox: ${MAILGUN_SANDBOX}
  from: ${MAILGUN_FROM}

chapa:
  secret-key: ${CHAPA_SECRET_KEY}
  base-url: ${CHAPA_BASE_URL}
  webhook-secret: ${CHAPA_WEBHOOK_SECRET}
  currency: ${CHAPA_CURRENCY}
  callback-url: ${CHAPA_CALLBACK_URL}
  return-url: ${CHAPA_RETURN_URL}
