spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

event-cache:
  enabled: ${EVENT_CACHE_ENABLED:true}
  prefix: ${EVENT_CACHE_PREFIX:event-cache}
  version: ${EVENT_CACHE_VERSION:v1}
