spring:
  application:
    name: api-gateway

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    hikari:
      keepalive-time: 30_000 # keep connection alive by testing them every 30s
      minimum-idle: 10 # ensure pool does not die when idle

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: false
#        trace: false

  sql:
    init:
      mode: ${SQL_MODE}
      schema-locations: classpath:schema.sql # runs 1st to create tables
      # enums-locations: classpath:enums.sql # runs 2nd
      # platform: h2

#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: none
#    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}


server:
  port: ${APP_PORT}

logging:
  config: classpath:api-gateway-logback-spring.xml
  level:
    root: INFO
    com.bicosteve.api_gateway: ${APP_LOGGING}
    org.springframework.jdbc: ${LOGGING_LEVEL}
    org.apache.coyote: ${APP_LOGGING}

mailgun:
  api-key: ${MAILGUN_API_KEY}
  base-url: ${MAILGUN_BASE_URL}
  sandbox: ${MAILGUN_SANDBOX}
  from: ${MAILGUN_FROM}

chapa:
  secret-key: ${CHAPA_SECRET_KEY}
  base-url: ${CHAPA_BASE_URL}
  webhook-secret: ${CHAPA_WEBHOOK_SECRET}
  currency: ${CHAPA_CURRENCY}
  callback-url: ${CHAPA_CALLBACK_URL}
  return-rul: ${CHAPA_RETURN_URL}







