name: Api Gateway CI

on:
    push:
        branches:
          - main
          - dev
          - "feat/*"
          - "fix/*"


    pull_request:
       branches:
         - dev
         - main

jobs:
     build:
         runs-on: ubuntu-latest

         steps:
           # STEP 1: Checkout repository
           - name: Checkout code
             uses: actions/checkout@v6

          # STEP 2: Set up JDK
           - name: Set up JDK 21
             uses: actions/setup-java@v5
             with:
               java-version: "21"
               distribution: "temurin"

          # STEP 3: Download & cache maven dependencies
           - name: Download & Cache Maven dependencies
             uses: actions/cache@v5
             with:
               path: ~/.m2/repository
               key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
               restore-keys: |
                 ${{ runner.os }}-maven-

          # STEP 6: Build the app to confirm everything is OK.
           - name: Build with Maven
             run: mvn -B package --file pom.xml
